"use client"

import { useRef, useState } from "react"
import { SectionEyebrow, SectionTitle } from "@/components/shared"
import { cn } from "@/lib/utils"

type ApyStage = {
  title: string
  description: string
  minApy: number
  maxApy: number
}

type HeatmapCell = {
  apy: number
  band: "inactive" | "base" | "premium" | "risk"
}

const APY_STAGES: readonly ApyStage[] = [
  {
    title: "Hub Base Rate",
    description: "Start with the base supplier yield generated by shared liquidity at the Avana Hub.",
    minApy: 0,
    maxApy: 3,
  },
  {
    title: "Spoke Premium",
    description: "LP-backed borrower demand in each spoke adds a second layer of APY on top of the hub floor.",
    minApy: 3,
    maxApy: 9,
  },
  {
    title: "Pool Risk Adjustment",
    description: "Specific pool risk contributes the final spread, lifting return potential for the same idle cash.",
    minApy: 9,
    maxApy: 20,
  },
] as const

const HEATMAP_ROWS = 5
const HEATMAP_COLUMNS_LINEAR = 20
const STAGE_FILLED_COUNTS = [20, 60, 100] as const
const BAND_COLORS = {
  inactive: "#eef2f6",
  base: "#d9eaff",
  premium: "#87b7ff",
  risk: "#2f84ff",
} as const

function buildHeatmap(stageIndex: number): HeatmapCell[][] {
  const stage = APY_STAGES[stageIndex]
  const filledCount = STAGE_FILLED_COUNTS[stageIndex]

  return Array.from({ length: HEATMAP_COLUMNS_LINEAR }, (_, column) =>
    Array.from({ length: HEATMAP_ROWS }, (_, row) => {
      const linearIndex = column * HEATMAP_ROWS + row
      const progress = linearIndex / (HEATMAP_COLUMNS_LINEAR * HEATMAP_ROWS - 1)
      const apy = Number((stage.minApy + progress * (stage.maxApy - stage.minApy)).toFixed(1))
      let band: HeatmapCell["band"] = "inactive"

      if (linearIndex < filledCount) {
        band = "base"
      }

      if (stageIndex >= 1 && linearIndex >= STAGE_FILLED_COUNTS[0] && linearIndex < STAGE_FILLED_COUNTS[1]) {
        band = "premium"
      }

      if (stageIndex >= 2 && linearIndex >= STAGE_FILLED_COUNTS[1]) {
        band = "risk"
      }

      return {
        apy,
        band,
      }
    }),
  )
}

export default function InvestApySection() {
  const [activeStageIndex, setActiveStageIndex] = useState(0)
  const activeStage = APY_STAGES[activeStageIndex]
  const heatmap = buildHeatmap(activeStageIndex)
  const touchStartX = useRef<number | null>(null)

  const handleTouchStart = (event: React.TouchEvent<HTMLDivElement>) => {
    touchStartX.current = event.touches[0]?.clientX ?? null
  }

  const handleTouchEnd = (event: React.TouchEvent<HTMLDivElement>) => {
    const startX = touchStartX.current
    const endX = event.changedTouches[0]?.clientX

    if (startX === null || endX === undefined) {
      touchStartX.current = null
      return
    }

    const deltaX = endX - startX
    const threshold = 40

    if (deltaX <= -threshold && activeStageIndex < APY_STAGES.length - 1) {
      setActiveStageIndex((current) => Math.min(current + 1, APY_STAGES.length - 1))
    }

    if (deltaX >= threshold && activeStageIndex > 0) {
      setActiveStageIndex((current) => Math.max(current - 1, 0))
    }

    touchStartX.current = null
  }

  return (
    <section className="bg-white py-16 md:py-20">
      <div className="site-content-shell">
        <div className="space-y-4">
          <SectionEyebrow tone="cyan">Avana APY</SectionEyebrow>
          <SectionTitle className="max-w-none text-[clamp(2.6rem,4.8vw,4rem)] leading-[0.95] md:whitespace-nowrap">
            Same Idle Cash with Higher APY Returns
          </SectionTitle>
        </div>

        <div className="mt-10">
          <div className="space-y-5">
            <div className="flex flex-wrap items-baseline gap-x-3 gap-y-1">
              <span className="text-[clamp(1.4rem,2vw,2rem)] font-semibold tracking-[-0.05em] text-[#163042]">
                {activeStage.minApy.toFixed(1)}% to {activeStage.maxApy.toFixed(1)}%
              </span>
              <span className="text-sm text-[#728196]">
                {activeStage.title}
              </span>
            </div>

            <div
              data-slot="apy-heatmap"
              className="touch-pan-y overflow-x-auto pb-1 [-ms-overflow-style:none] [scrollbar-width:none] [&::-webkit-scrollbar]:hidden"
              onTouchStart={handleTouchStart}
              onTouchEnd={handleTouchEnd}
            >
              <div className="flex min-w-max w-full gap-2.5 md:gap-3">
                {heatmap.map((column, columnIndex) => (
                  <div key={`column-${columnIndex}`} className="flex min-w-[0.95rem] flex-1 flex-col gap-2.5 md:min-w-[1.1rem] md:gap-3">
                    {column.map((cell, rowIndex) => (
                      <div
                        key={`cell-${columnIndex}-${rowIndex}`}
                        data-slot="apy-cell"
                        data-band={cell.band}
                        data-active={cell.band !== "inactive"}
                        aria-label={`${cell.apy.toFixed(1)}% APY`}
                        className="aspect-square w-full rounded-[5px] transition-colors duration-500"
                        style={{ backgroundColor: BAND_COLORS[cell.band] }}
                      />
                    ))}
                  </div>
                ))}
              </div>
            </div>
          </div>

          <div className="mt-8 grid grid-cols-3 gap-4 md:gap-8">
            {APY_STAGES.map((stage, index) => {
              const active = index === activeStageIndex

              return (
                <button
                  key={stage.title}
                  type="button"
                  aria-pressed={active}
                  onClick={() => setActiveStageIndex(index)}
                  className="flex min-h-[5rem] flex-col items-start text-left md:min-h-[8rem]"
                >
                  <div
                    className={cn(
                      "mb-5 h-[3px] w-full rounded-full transition-colors duration-200",
                      active ? "bg-[#2f84ff]" : "bg-[#eceff3]",
                    )}
                  />
                  <h3
                    className={cn(
                      "text-[clamp(0.92rem,3.6vw,1.9rem)] font-semibold leading-[1.06] tracking-[-0.05em] transition-colors duration-200",
                      active ? "text-[#2f84ff]" : "text-[#9ea3aa]",
                    )}
                  >
                    {stage.title}
                  </h3>
                  {active ? (
                    <p className="mt-4 hidden max-w-[20rem] text-base leading-[1.7] text-[#6f7681] md:block">
                      {stage.description}
                    </p>
                  ) : null}
                </button>
              )
            })}
          </div>

          <p className="mt-4 text-sm leading-[1.7] text-[#6f7681] md:hidden">
            {activeStage.description}
          </p>
        </div>
      </div>
    </section>
  )
}
