# Part 3: strings 21-50 (ja, ko, ru, tr, uk) - continued in LONG_5
from scripts._blog_a_translations_part2 import LONG_5

LONG_5.update({
    "On Avana, LP collateral is active, path dependent, and operationally demanding. It earns fees, shifts composition, changes risk as markets move, and can require venue specific actions exactly when a position becomes stressed. A standard token market can often reduce liquidation and monitoring to a simpler trigger and swap path. LP collateral is different. The system has to know which positions are active, how debt is drifting, what the collateral would look like under a real unwind, how fees can be realized, which venue specific removal path applies, and whether liquidation is still viable after slippage, routing, and execution cost. Those details are what separate theoretical coverage on paper from coverage that still works when markets get hard.": {
        "ja": "Avanaでは、LP担保はアクティブで、パス依存であり、運用上要求が高いものです。手数料を稼ぎ、構成が変わり、市場の動きに応じてリスクが変化し、ポジションがストレスを受けるまさにその時にvenue固有のアクションが必要になることがあります。標準的なトークン市場は、清算とモニタリングをより単純なトリガーとスワップパスに還元できることが多いです。LP担保は異なります。システムはどのポジションがアクティブか、負債がどう漂流しているか、実際のアンウィンド下で担保がどう見えるか、手数料をどう実現できるか、どのvenue固有の除去パスが適用されるか、スリッページ、ルーティング、実行コスト後も清算が実行可能かを知る必要があります。これらの詳細が、紙上の理論的カバレッジと、市場が厳しくなっても機能するカバレッジを分けます。",
        "ko": "Avana에서 LP 담보는 활성적이고, 경로 의존적이며, 운영상 까다롭습니다. 수수료를 벌고, 구성이 변하며, 시장이 움직이면서 리스크가 바뀌고, 포지션이 스트레스를 받을 때 정확히 venue별 조치가 필요할 수 있습니다. 표준 토큰 시장은 청산과 모니터링을 더 단순한 트리거와 스왑 경로로 줄일 수 있는 경우가 많습니다. LP 담보는 다릅니다. 시스템은 어떤 포지션이 활성인지, 부채가 어떻게 표류하는지, 실제 unwind 하에서 담보가 어떻게 보이는지, 수수료를 어떻게 실현할 수 있는지, 어떤 venue별 제거 경로가 적용되는지, 슬리피지, 라우팅, 실행 비용 후에도 청산이 가능한지 알아야 합니다. 이러한 세부 사항이 이론적 커버리지와 시장이 어려워져도 작동하는 커버리지를 구분합니다.",
        "ru": "На Avana LP-залог активен, зависит от пути и требователен в эксплуатации. Он приносит комиссии, меняет состав, изменяет риск по мере движения рынков и может требовать venue-специфичных действий именно когда позиция находится под стрессом. Стандартный токен-рынок часто сводит ликвидацию и мониторинг к более простому триггеру и swap-пути. LP-залог другой. Система должна знать, какие позиции активны, как дрейфует долг, как будет выглядеть залог при реальном unwind, как можно реализовать комиссии, какой venue-специфичный путь удаления применим и остаётся ли ликвидация жизнеспособной после slippage, маршрутизации и стоимости исполнения. Эти детали отделяют теоретическое покрытие на бумаге от покрытия, которое работает, когда рынки ужесточаются.",
        "tr": "Avana'da LP teminatı aktif, yol bağımlı ve operasyonel olarak zorludur. Ücret kazanır, bileşim değişir, piyasalar hareket ettikçe risk değişir ve bir pozisyon stres altına girdiğinde tam o anda venue'ye özgü eylemler gerekebilir. Standart bir token piyasası likidasyon ve izlemeyi genellikle daha basit bir tetikleyici ve swap yoluna indirgeyebilir. LP teminatı farklıdır. Sistem hangi pozisyonların aktif olduğunu, borcun nasıl sürüklendiğini, gerçek bir unwind altında teminatın nasıl görüneceğini, ücretlerin nasıl gerçekleştirilebileceğini, hangi venue'ye özgü çıkarma yolunun geçerli olduğunu ve slippage, yönlendirme ve yürütme maliyetinden sonra likidasyonun hâlâ uygulanabilir olup olmadığını bilmelidir. Bu ayrıntılar, kağıt üzerindeki teorik kapsamı piyasalar zorlaştığında hâlâ çalışan kapsamdan ayırır.",
        "uk": "На Avana LP-застава активна, залежить від шляху й вимоглива в експлуатації. Вона приносить комісії, змінює склад, змінює ризик у міру руху ринків і може вимагати venue-специфічних дій саме коли позиція під стресом. Стандартний токен-ринок часто зводить ліквідацію й моніторинг до простішого тригера та swap-шляху. LP-застава інша. Система має знати, які позиції активні, як дрейфує борг, як виглядатиме застава при реальному unwind, як можна реалізувати комісії, який venue-специфічний шлях видалення застосовний і чи залишається ліквідація життєздатною після slippage, маршрутизації та вартості виконання. Ці деталі відокремлюють теоретичне покриття на папері від покриття, яке працює, коли ринки ускладнюються.",
    },
    "What Avana Smart Agents do": {
        "ja": "Avana Smart Agentsの役割",
        "ko": "Avana Smart Agents가 하는 일",
        "ru": "Что делают Avana Smart Agents",
        "tr": "Avana Smart Agents ne yapar",
        "uk": "Що роблять Avana Smart Agents",
    },
    "Avana's node runtime reads onchain activity, keeps a live map of active positions, refreshes drifting debt on short intervals, and runs broader sweeps to catch stale or missed state. The app UI, dashboards, monitoring logic, and liquidation workflows are meant to draw from that same operational picture, rather than each layer inventing its own version of the market.": {
        "ja": "Avanaのノードランタイムはオンチェーン活動を読み取り、アクティブなポジションのライブマップを維持し、短い間隔で漂流する負債を更新し、古いまたは見逃された状態を捕捉するための広範なスイープを実行します。アプリUI、ダッシュボード、モニタリングロジック、清算ワークフローは、各レイヤーが独自の市場バージョンを作るのではなく、この同じ運用像から描画されることを意図しています。",
        "ko": "Avana의 노드 런타임은 온체인 활동을 읽고, 활성 포지션의 라이브 맵을 유지하며, 짧은 간격으로 표류하는 부채를 갱신하고, 오래되거나 누락된 상태를 잡기 위한 광범위한 스윕을 실행합니다. 앱 UI, 대시보드, 모니터링 로직, 청산 워크플로는 각 계층이 자체 시장 버전을 만들기보다 이 동일한 운영 그림에서 그려지도록 설계되었습니다.",
        "ru": "Node runtime Avana читает onchain-активность, ведёт живую карту активных позиций, обновляет дрейфующий долг на коротких интервалах и выполняет более широкие проходы для обнаружения устаревшего или пропущенного состояния. UI приложения, дашборды, логика мониторинга и workflow ликвидации должны опираться на ту же операционную картину, а не каждый слой изобретает свою версию рынка.",
        "tr": "Avana'nın node runtime'ı onchain aktiviteyi okur, aktif pozisyonların canlı haritasını tutar, sürüklenen borcu kısa aralıklarla yeniler ve eski veya kaçırılmış durumu yakalamak için daha geniş taramalar yapar. Uygulama UI'sı, panolar, izleme mantığı ve likidasyon iş akışları, her katmanın kendi piyasa versiyonunu icat etmesi yerine aynı operasyonel tablodan beslenmek üzere tasarlanmıştır.",
        "uk": "Node runtime Avana читає onchain-активність, веде живу карту активних позицій, оновлює дрейфуючий борг на коротких інтервалах і виконує ширші проходи для виявлення застарілого або пропущеного стану. UI додатка, дашборди, логіка моніторингу та workflow ліквідації мають спиратися на ту саму операційну картину, а не кожен шар вигадує власну версію ринку.",
    },
    "Liquidation is where this matters most. When an Avana position falls below allowed borrowing capacity, the execution layer has to evaluate whether the job can be serviced profitably, source temporary liquidity, repay debt into the credit layer, claim fees, unwind the collateral through the correct venue path, route the resulting assets, settle the flash path, distribute the liquidation premium, and preserve borrower residual value when anything remains. That is a chain of work, not a single transaction type.": {
        "ja": "清算はここが最も重要です。Avanaポジションが許容借入容量を下回ると、実行レイヤーはジョブが利益を出して処理できるか評価し、一時的な流動性を調達し、クレジットレイヤーに負債を返済し、手数料を請求し、正しいvenueパスで担保をアンウィンドし、結果の資産をルーティングし、フラッシュパスを決済し、清算プレミアムを分配し、残りがあれば借り手の残余価値を保持する必要があります。これは単一のトランザクションタイプではなく、作業の連鎖です。",
        "ko": "청산은 여기서 가장 중요합니다. Avana 포지션이 허용 차입 용량 아래로 떨어지면 실행 계층은 작업을 수익성 있게 처리할 수 있는지 평가하고, 임시 유동성을 조달하며, 신용 계층에 부채를 상환하고, 수수료를 청구하고, 올바른 venue 경로로 담보를 unwind하며, 결과 자산을 라우팅하고, 플래시 경로를 정산하고, 청산 프리미엄을 분배하며, 남은 것이 있으면 차입자 잔여 가치를 보존해야 합니다. 이것은 단일 트랜잭션 유형이 아니라 작업의 연쇄입니다.",
        "ru": "Ликвидация — здесь это важнее всего. Когда позиция Avana падает ниже допустимой заёмной ёмкости, слой исполнения должен оценить, можно ли обслужить задачу с прибылью, найти временную ликвидность, погасить долг в кредитном слое, забрать комиссии, развернуть залог через правильный venue-путь, маршрутизировать полученные активы, закрыть flash-путь, распределить премию ликвидации и сохранить остаточную стоимость заёмщика, если что-то остаётся. Это цепочка работ, а не один тип транзакции.",
        "tr": "Likidasyon burada en çok önem taşır. Bir Avana pozisyonu izin verilen borçlanma kapasitesinin altına düştüğünde, yürütme katmanı işin kârlı şekilde hizmet edilip edilemeyeceğini değerlendirmeli, geçici likidite sağlamalı, borcu kredi katmanına geri ödemeli, ücretleri talep etmeli, teminatı doğru venue yoluyla çözmeli, ortaya çıkan varlıkları yönlendirmeli, flash yolunu kapatmalı, likidasyon primini dağıtmalı ve kalan bir şey varsa borçlunun artık değerini korumalıdır. Bu tek bir işlem türü değil, bir iş zinciridir.",
        "uk": "Ліквідація — тут це найважливіше. Коли позиція Avana падає нижче дозволеної позикової ємності, шар виконання має оцінити, чи можна обслуговувати завдання з прибутком, знайти тимчасову ліквідність, погасити борг у кредитному шарі, забрати комісії, розгорнути заставу через правильний venue-шлях, маршрутизувати отримані активи, закрити flash-шлях, розподілити премію ліквідації й зберегти залишкову вартість позичальника, якщо щось залишається. Це ланцюг робіт, а не один тип транзакції.",
    },
    "Before liquidation, and across venues": {
        "ja": "清算前、そしてvenueを横断して",
        "ko": "청산 전, 그리고 venue 전반에서",
        "ru": "До ликвидации и между venue",
        "tr": "Likidasyondan önce ve venue'ler arasında",
        "uk": "До ліквідації та між venue",
    },
    "Smart Agents also matter before liquidation happens. Indexing Avana positions, watching debt drift, and keeping the protocol aligned with its own oracle and risk assumptions improve readiness. Operational delay is not free when collateral keeps moving with the market.": {
        "ja": "Smart Agentsは清算が起きる前にも重要です。Avanaポジションのインデックス化、負債漂流の監視、プロトコルを自身のオラクルとリスク前提に整合させることで、準備態勢が向上します。担保が市場とともに動き続けるとき、運用の遅延は無料ではありません。",
        "ko": "Smart Agents는 청산이 발생하기 전에도 중요합니다. Avana 포지션 인덱싱, 부채 표류 감시, 프로토콜을 자체 오라클 및 리스크 가정에 맞추는 것이 준비 상태를 개선합니다. 담보가 시장과 함께 계속 움직일 때 운영 지연은 공짜가 아닙니다.",
        "ru": "Smart Agents важны и до ликвидации. Индексация позиций Avana, наблюдение за дрейфом долга и поддержание протокола в соответствии с собственными допущениями оракулов и риска повышают готовность. Операционная задержка не бесплатна, когда залог продолжает двигаться вместе с рынком.",
        "tr": "Smart Agents likidasyon gerçekleşmeden önce de önemlidir. Avana pozisyonlarını indekslemek, borç sürüklenmesini izlemek ve protokolü kendi oracle ve risk varsayımlarıyla uyumlu tutmak hazırlığı artırır. Teminat piyasayla hareket etmeye devam ettiğinde operasyonel gecikme bedelsiz değildir.",
        "uk": "Smart Agents важливі й до ліквідації. Індексація позицій Avana, спостереження за дрейфом боргу та підтримка протоколу відповідно до власних припущень оракулів і ризику підвищують готовність. Операційна затримка не безкоштовна, коли застава продовжує рухатися разом із ринком.",
    },
    "LP collateral is an adapter problem as much as a valuation problem. Fungible LPs, concentrated ranges, and custom pool designs need different venue aware handling. Smart Agents are Avana's layer for respecting those differences instead of forcing one generic pathway onto every market. The oracle tells Avana what a position might be worth as credit. The agent layer helps determine whether that value can actually be recovered in practice.": {
        "ja": "LP担保は評価問題と同時にアダプター問題でもあります。代替可能なLP、集中レンジ、カスタムプール設計には異なるvenue対応の処理が必要です。Smart Agentsは、すべての市場に汎用パスを強制するのではなく、これらの違いを尊重するAvanaのレイヤーです。オラクルはポジションがクレジットとしてどれだけの価値があるかをAvanaに伝えます。エージェントレイヤーは、その価値が実際に回収可能かを判断するのに役立ちます。",
        "ko": "LP 담보는 평가 문제만큼 어댑터 문제입니다. 대체 가능한 LP, 집중 범위, 커스텀 풀 설계는 서로 다른 venue 인식 처리가 필요합니다. Smart Agents는 모든 시장에 하나의 범용 경로를 강제하는 대신 이러한 차이를 존중하는 Avana의 계층입니다. 오라클은 포지션이 신용으로 얼마나 가치 있는지 Avana에 알려줍니다. 에이전트 계층은 그 가치가 실제로 회수 가능한지 판단하는 데 도움을 줍니다.",
        "ru": "LP-залог — это проблема адаптеров не меньше, чем проблема оценки. Взаимозаменяемые LP, концентрированные диапазоны и кастомные дизайны пулов требуют разной venue-осведомлённой обработки. Smart Agents — слой Avana для уважения этих различий вместо навязывания одного универсального пути каждому рынку. Оракул говорит Avana, сколько позиция может стоить как кредит. Слой агентов помогает определить, можно ли эту стоимость реально восстановить на практике.",
        "tr": "LP teminatı bir değerleme sorunu kadar bir adaptör sorunudur. Değiştirilebilir LP'ler, konsantre aralıklar ve özel havuz tasarımları farklı venue farkındalıklı işlem gerektirir. Smart Agents, her piyasaya tek bir genel yol zorlamak yerine bu farklara saygı duyan Avana katmanıdır. Oracle, bir pozisyonun kredi olarak ne kadar değerli olabileceğini Avana'ya söyler. Ajan katmanı bu değerin pratikte gerçekten kurtarılıp kurtarılamayacağını belirlemeye yardımcı olur.",
        "uk": "LP-застава — це проблема адаптерів не менше, ніж проблема оцінки. Взаємозамінні LP, концентровані діапазони та кастомні дизайни пулів потребують різної venue-обізнаної обробки. Smart Agents — шар Avana для поваги до цих відмінностей замість нав'язування одного універсального шляху кожному ринку. Оракул каже Avana, скільки позиція може коштувати як кредит. Шар агентів допомагає визначити, чи можна цю вартість реально відновити на практиці.",
    },
    "Avana does not replace permissionless liquidation. External builders can still monitor and act. Protocol operated runtimes improve baseline coverage for collateral that is structurally harder to service. In stress that matters a lot. The worst moment to discover that a market lacks reliable execution coverage is during the liquidation event itself.": {
        "ja": "Avanaはパーミッションレス清算を置き換えません。外部ビルダーは引き続き監視し行動できます。プロトコル運用のランタイムは、構造的にサービスが難しい担保のベースラインカバレッジを改善します。ストレス時にはそれが大きく重要になります。市場に信頼できる実行カバレッジがないことを発見する最悪の瞬間は、清算イベントそのものの最中です。",
        "ko": "Avana는 무허가 청산을 대체하지 않습니다. 외부 빌더는 여전히 모니터링하고 행동할 수 있습니다. 프로토콜 운영 런타임은 구조적으로 서비스하기 어려운 담보의 기본 커버리지를 개선합니다. 스트레스 상황에서 이는 매우 중요합니다. 시장에 신뢰할 수 있는 실행 커버리지가 없다는 것을 발견하는 최악의 순간은 청산 이벤트 자체입니다.",
        "ru": "Avana не заменяет permissionless ликвидацию. Внешние билдеры по-прежнему могут мониторить и действовать. Управляемые протоколом runtime улучшают базовое покрытие для залога, который структурно сложнее обслуживать. Под стрессом это очень важно. Худший момент обнаружить, что у рынка нет надёжного покрытия исполнения — во время самого события ликвидации.",
        "tr": "Avana izinsiz likidasyonun yerini almaz. Harici geliştiriciler hâlâ izleyebilir ve harekete geçebilir. Protokol tarafından işletilen runtime'lar, yapısal olarak hizmet vermesi daha zor teminat için temel kapsamı iyileştirir. Stres altında bu çok önemlidir. Bir piyasanın güvenilir yürütme kapsamından yoksun olduğunu keşfetmenin en kötü anı, likidasyon olayının kendisidir.",
        "uk": "Avana не замінює permissionless ліквідацію. Зовнішні білдери досі можуть моніторити й діяти. Керовані протоколом runtime покращують базове покриття для застави, яку структурно важче обслуговувати. Під стресом це дуже важливо. Найгірший момент виявити, що ринок не має надійного покриття виконання — під час самої події ліквідації.",
    },
    "Not a simple token sale": {
        "ja": "単純なトークン売却ではない",
        "ko": "단순한 토큰 매도가 아니다",
        "ru": "Не простая продажа токена",
        "tr": "Basit bir token satışı değil",
        "uk": "Не простий продаж токена",
    },
    "Liquidating LP collateral on Avana is not the same as liquidating a token balance. The collateral may contain multiple assets, uncollected fees, concentrated range exposure, and venue specific exit mechanics. If a position becomes unhealthy, Avana needs a controlled unwind, not a panic sale that treats the LP like a single fungible chip.": {
        "ja": "AvanaでのLP担保の清算は、トークン残高の清算と同じではありません。担保には複数の資産、未回収の手数料、集中レンジのエクスポージャー、venue固有の出口メカニズムが含まれる場合があります。ポジションが不健全になると、AvanaにはLPを単一の代替可能チップのように扱うパニック売りではなく、制御されたアンウィンドが必要です。",
        "ko": "Avana에서 LP 담보 청산은 토큰 잔액 청산과 같지 않습니다. 담보에는 여러 자산, 미수령 수수료, 집중 범위 노출, venue별 출구 메커니즘이 포함될 수 있습니다. 포지션이 불건전해지면 Avana는 LP를 단일 대체 가능 칩처럼 다루는 패닉 매도가 아니라 통제된 unwind가 필요합니다.",
        "ru": "Ликвидация LP-залога на Avana — не то же самое, что ликвидация баланса токена. Залог может содержать несколько активов, несобранные комиссии, экспозицию концентрированного диапазона и venue-специфичную механику выхода. Если позиция становится нездоровой, Avana нужен контролируемый unwind, а не паническая продажа, относящаяся к LP как к одной взаимозаменяемой фишке.",
        "tr": "Avana'da LP teminatını likide etmek, bir token bakiyesini likide etmekle aynı değildir. Teminat birden fazla varlık, toplanmamış ücretler, konsantre aralık maruziyeti ve venue'ye özgü çıkış mekanizmaları içerebilir. Bir pozisyon sağlıksız hale gelirse Avana'nın LP'yi tek bir değiştirilebilir fiş gibi ele alan panik satışı değil, kontrollü bir unwind'a ihtiyacı vardır.",
        "uk": "Ліквідація LP-застави на Avana — не те саме, що ліквідація балансу токена. Застава може містити кілька активів, невибрані комісії, експозицію концентрованого діапазону та venue-специфічну механіку виходу. Якщо позиція стає нездоровою, Avana потребує контрольованого unwind, а не панічного продажу, що ставиться до LP як до однієї взаємозамінної фішки.",
    },
    "The runtime sequence": {
        "ja": "ランタイムシーケンス",
        "ko": "런타임 시퀀스",
        "ru": "Последовательность runtime",
        "tr": "Runtime sırası",
        "uk": "Послідовність runtime",
    },
})
